before_script:
  - "bundle exec rake test:generate_certs"
  - "nohup bundle exec ruby test/live_server.rb &"
  - "sleep 2"

env:
 - LIVE=http://localhost:4567
 - LIVE=https://localhost:4567

language: ruby

matrix:
  allow_failures:
    - rvm: ruby-head

rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
